site_name: Nexus Plugin Framework Documentation
site_url: https://thenexusavenger.github.io/Nexus-Plugin-Framework
repo_name: TheNexusAvenger/Nexus-Plugin-Framework
repo_url: https://github.com/TheNexusAvenger/Nexus-Plugin-Framework

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Classes:
    - NexusWrappedInstance: classes/NexusPluginFramework.md
    - Base:
      - OverridableIndexInstance: classes/Base/OverridableIndexInstance.md
      - NexusContainer: classes/Base/NexusContainer.md
      - NexusDisablableContainer: classes/Base/NexusDisablableContainer.md
      - NexusWrappedInstance: classes/Base/NexusWrappedInstance.md
    - Data:
      - Enum:
        - NexusEnum: classes/Data/Enum/NexusEnum.md
        - NexusEnumCollection: classes/Data/Enum/NexusEnumCollection.md
    - Plugin:
      - NexusPlugin: classes/Plugin/NexusPlugin.md
      - NexusPluginButton: classes/Plugin/NexusPluginButton.md
      - NexusPluginGui: classes/Plugin/NexusPluginGui.md
      - NexusPluginToolbar: classes/Plugin/NexusPluginToolbar.md
      - NexusSettings: classes/Plugin/NexusSettings.md
      - NexusStudioTheme: classes/Plugin/NexusStudioTheme.md
      - NexusUserInput: classes/Plugin/NexusUserInput.md
    - UI:
      - CollapsableList:
        - NexusCollapsableListFrame: classes/UI/CollapsableList/NexusCollapsableListFrame.md
        - Constraint:
          - NexusCollapsableListFrameConstraint: classes/UI/CollapsableList/Constraint/NexusCollapsableListFrameConstraint.md
          - NexusContentsPropertyConstraint: classes/UI/CollapsableList/Constraint/NexusContentsPropertyConstraint.md
          - NexusMultiConstraint: classes/UI/CollapsableList/Constraint/NexusMultiConstraint.md
          - NexusSelectionConstraint: classes/UI/CollapsableList/Constraint/NexusSelectionConstraint.md
      - Constraint:
        - NexusBoundingSizeConstraint: classes/UI/Constraint/NexusBoundingSizeConstraint.md
      - Input:
        - NexusCheckBox: classes/UI/Input/NexusCheckBox.md
        - NexusImageButton: classes/UI/Input/NexusImageButton.md
        - NexusTextBox: classes/UI/Input/NexusTextBox.md
        - NexusTextButton: classes/UI/Input/NexusTextButton.md
        - Abstract:
          - NexusGuiButton: classes/UI/Input/Abstract/NexusGuiButton.md
      - Scroll:
        - NexusScrollBar: classes/UI/Scroll/NexusScrollBar.md
        - NexusScrollingFrame: classes/UI/Scroll/NexusScrollingFrame.md
  - Examples:
    - Toolbar: examples/toolbar.md
    - Collapsable List: examples/collapsable-list.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite